### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by xx7Ahmed7xx** [Bassantyasser043/Email-server#1]
Hello there dear engineers, How can I contact you? email? linkedin? whatsapp?

**Comment by Bassantyasser043** [comment]
you can contact me either through linkendin: https://www.linkedin.com/in/bassant-yasser-0b59a61b1/
gmail: Bassantmohamed043@gmail.com

**Comment by xx7Ahmed7xx** [comment]
Thank you, contacted
